Neos:
  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 0
    fusion:
      autoInclude:
        Malyshev.Site: true
